### ISSUE TITLE
Upgrade to Frequency api-augment v1.13.0+

### ISSUE THREAD

**Issue by wilwade** [ProjectLibertyLabs/reconnection-service#206]
- [x] Supports new Frequency Runtime v110 (v1.13.0)
- [ ] Still works with Frequency Runtimes < v110
- [x] Upgrade any `npm audit` finds if possible

**Comment by saraswatpuneet** [comment]
Is there a change in how types are imported? 

this does not seems to be supported in 1.13 and polakdot 13.1.1+

Might have to import directly from augment

**Comment by wilwade** [comment]
@saraswatpuneet it should still work. Might need to clear the node_modules first.

**Comment by saraswatpuneet** [comment]
I did and getting build errors
* cleaned the npm cache and deleted node_modules
* npm i
* npm run build


![image](https://github.com/user-attachments/assets/d5d4a9b7-e2d8-46ea-b58b-6ee714110132)

**Comment by saraswatpuneet** [comment]
Am i using correct version?

    "@frequency-chain/api-augment": "`^1.13.0"`,

or its `1.30`?

**Comment by wilwade** [comment]
Updated title and desc.

You are correct it is `v1.13.0`

You'll want to make sure that we pin Polkadotjs API to the same version as augment v1.13.0 has
